stages:
  - test
  - cml_run
  - pages

# image: python:3.7-slim
image: dvcorg/cml-py3:latest

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

cml:
  stage: cml_run
  script:
    - dvc pull
    - dvc repro
    - git fetch --prune
    - echo "# Parameter List" >> report.md
    - dvc metrics diff --show-md develop >> report.md
    - echo "# ROC-Curve" >> report.md
    - dvc plots diff --target roc.csv --show-vega develop -x fpr -y tpr > vega.json
    - vl2png vega.json -s 1.5 | cml-publish --md  >> report.md
    - cml-tensorboard-dev --logdir model/logs --name "Go to tensorboard" --md >> report.md
    - cml-send-comment report.md
    - python src/pulsed_power_ml/train_tensorboard.py

pages:
  script:
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public



