stages:
  - test

image: python:3.7-slim

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pytest --junitxml=report.xml
    artifacts:
      when: always
      reports:
        junit: report.xml