trigger:
- master
- develop

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: |
    pip install -r requirements.txt
  displayName: 'install requirements'

- script: |
    pytest
  displayName: 'run tests'
