trigger:
- master
- develop

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- script: |
    pip install -r requirements.txt
  displayName: 'install requirements'

- script: |
    pytest
  displayName: 'run tests'

- task: CmdLine@2
  inputs:
    script: 'make html' 
    workingDirectory: '$(Build.SourcesDirectory)/docs/' 
  displayName: 'Compile documentation'


- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/docs/_build/html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '**'
  displayName: 'Copy documentation files to artifact directory'

- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    vstsFeedPublish: 'kol_db/documentation'
    vstsFeedPackagePublish: 'doku'
    packagePublishDescription: 'sphinx documentation'
